version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:14
jobs:
  build-and-test-backend:
    executor: node-executor
    steps:
      - checkout
      - run: cd backend && npm install
      - run: cd backend && npm test
  build-and-test-frontend:
    executor: node-executor
    steps:
      - checkout
      - run: cd frontend && npm install
      - run: cd frontend && npm test
  deploy-backend:
    executor: node-executor
    steps:
      - checkout
      - run: cd backend && npm run build
      - run: # add your deployment commands here
  deploy-frontend:
    executor: node-executor
    steps:
      - checkout
      - run: cd frontend && npm run build
      - run: # add your deployment commands here
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test-backend
      - build-and-test-frontend
      - deploy-backend:
          requires:
            - build-and-test-backend
      - deploy-frontend:
          requires:
            - build-and-test-frontend
