version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "14.15"
      - checkout
      ## Install front-end dependencies
      - run:
          name: Front-end dependencies
          command: |
            npm run frontend:install
      ## Install back-end dependencies
      - run:
          name: Back-end Dependencies
          command: |
            npm run api:install
      ## Build the front-end
      - run:
          name: Front-end Build
          command: |
            npm run frontend:build
      # Build the back-end
      - run:
          name: Back-end Build
          command: |
            npm run api:build
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "14.15"
      - eb/setup
      - aws-cli/setup
      - checkout
      # Deploy back-end &  front-end
      - run:
          name: Deployment
          command: |
            npm run api:deploy
            npm run frontend:deploy
workflows:
  deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - hold
